### ISSUE TITLE
React Workshop - ToDo's

### ISSUE THREAD

**Issue by andrewdamelio** [rangle/react-workshop#1]
Moving forward - please submit any of the belw

**Todo App**
 - [x] Complete it 
 - [x] Flux-ify it
(**Sumit has been working on this - please coordinate with him if you wanna help complete it**)
 - [x] refactor and adjust (align with best practices)
 - [ ] restyle the app, give it a Rangle look and feel
 - [x] Write unit test for Todo App

---

**Topics that require write ups:**

- [x]  Write up on an overview of WebPack - brief blurb for the toolkit section **[WIP: Seth]**
- [x]  Write up on an overview of ImmutableJS **[WIP: Andrej]**
       - Mutable vs. Immutable
       - Persistent Data Structures?
       - Structure Data Sharing
       - ImmutableJS API
       - Build it into todo App (undo, time machine)
- [x]  Write up on the differences between Jest versus JSDom
- [ ]  Write up on Flux... **[WIP: Andrej]**
       - What is a Action?
       - What is a Store?
       - What is a Dispatcher?
       - MVC vs Flux
- [x]  Write up on what a Observables is.

---
**Complete Workshop Sections:**
- [x]  1. Getting started with ReactJS **[WIP - Andrew D]**
- [x]  2. Composing components.  **[WIP - Andrew D]**
- [ ]  3. Unit testing ReactJS components. **[WIP - Sumit]**
- [ ]  4. Flux architecture.
- [ ] 5. Building a Flux Application using TDD.

---
**Peer-Review Workshop Sections: Pending completion of the above**
- [x]  1. Getting started with ReactJS
- [ ]  2. Composing components.
- [ ]  3. Unit testing ReactJS components.
- [ ]  4. Flux architecture.
- [ ] 5. Building a Flux Application using TDD.

**Comment by SethDavenport** [comment]
I can do 'Write up on a overview of WebPack - brief blurb for the toolkit
section'

When do you need it done by?

Seth

On Mon, Aug 24, 2015 at 4:13 AM, andrewdamelio <notifications@github.com>
wrote:

> Moving forward - please submit any of the belw
>
> *Todo App*
>
>    - Complete it (*Sumit has been working on this - please coordinate
>    with him if you wanna help complete it*)
>    - refactor and adjust (align with best practices)
>    - restyle the app, give it a Rangle look and feel
>    - Write unit test for Todo App
>
> ------------------------------
>
> *Topics that require write ups:*
>
>    - Write up on a overview of WebPack - brief blurb for the toolkit
>    section
>    - Write up on a overview of ImmutableJS
>       - Mutable vs. Immutable
>       - Persistent Data Structures?
>       - Structure Data Sharing
>       - ImmutableJS API
>    - Write up on the differences between Jest versus JSDom
>    - Write up on Flux...
>       - What is a Action?
>       - What is a Store?
>       - What is a Dispatcher?
>       - MVC vs Flux
>    - Write up on what a Observables is.
>
> ------------------------------
>
> *Complete Workshop Sections:*
>
>    - 1. Getting started with ReactJS *[WIP - Andrew D]*
>    - 2. Composing components. *[WIP - Andrew D]*
>    - 3. Unit testing ReactJS components. *[WIP - Sumit]*
>    - 4. Flux architecture.
>    - 5. Building a Flux Application using TDD.
>
> ------------------------------
>
> *Peer-Review Workshop Sections: Pending completion of the above*
>
>    - 1. Getting started with ReactJS
>    - 2. Composing components.
>    - 3. Unit testing ReactJS components.
>    - 4. Flux architecture.
>    - 5. Building a Flux Application using TDD.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rangle/react-workshop/issues/1>.
>



-- 
Software Developer
Skype: seth.rangleio
Tel: +1 416 737 1555 x1057

*Rangle.io <http://rangle.io/> -** Rewriting the Web*
Phone: 416-737-1555  |  1-844-467-2645
Mail: 150 John Street, # 501, Toronto, ON. M5V 3E3
*Connect with us!*
Blog <http://rangle.io/blog/> | Twitter <https://twitter.com/rangleio> |
LinkedIn <http://www.linkedin.com/company/5018494>  | Google+
<https://plus.google.com/+rangleio/posts> | Facebook
<https://www.facebook.com/rangle.io>

**Comment by andrejkn** [comment]
I will work on 'Write up on an overview of ImmutableJS'

**Comment by andrewdamelio** [comment]
Thanks y'all!
